### ISSUE TITLE
[FIX] vars file for Ubuntu 20.04

### ISSUE THREAD

**Issue by klemens-u** [aalaesar/install_nextcloud#106]
Untested!

[Ubuntu-focal.yml.zip](https://github.com/aalaesar/install_nextcloud/files/5621159/Ubuntu-focal.yml.zip)

**Comment by wiktor2200** [comment]
It's already added in: https://github.com/aalaesar/install_nextcloud/blob/master/vars/Ubuntu-focal.yml with commit: https://github.com/aalaesar/install_nextcloud/commit/8ab88c5c4cda38507c74acd1a6bffeeff36edf11
so I think this issue can be closed.
