### ISSUE TITLE
Add option to choose PHP variant (Apache module vs. FPM)

### ISSUE THREAD

**Issue by klemens-u** [aalaesar/install_nextcloud#107]
Using Ubuntu 18.04 this role installs PHP with classic Apache module. Nextcloud recommends to use PHP-FPM.
It would be nice if the role could support this.

Attached you find what I run after your role to switch to FPM.

Perhaps we can integrate this together.

[php_fpm.yml.zip](https://github.com/aalaesar/install_nextcloud/files/5621195/php_fpm.yml.zip)
[handlers.zip](https://github.com/aalaesar/install_nextcloud/files/5621201/handlers.zip)

**Comment by staticdev** [comment]
@klemens-u I was just checking old issues. I am sure this role is now covering FPM, try our latest 1.6.0 version to see.
