### ISSUE TITLE
When php version is changed, the nginx is not restarted

### ISSUE THREAD

**Issue by mihailstoynov** [aalaesar/install_nextcloud#109]
When I change the php version and the php_handler is updated in nginx, nginx itself is not restarted

**Comment by aalaesar** [comment]
Hi @mihailstoynov  thx for the feedback
can you elaborate the issue please ?
I noted the notify directive in the template tasks so "in theory" it should reload nginx, unless reload is not enough

**Comment by mihailstoynov** [comment]
I noticed the `notify`. But for some reason it didn't work. I haven't saved any logs.
nginx restart is sufficient.
I guess you can close this one and I'll reopen it if I have more info.

**Comment by aalaesar** [comment]
> I guess you can close this one and I'll reopen it if I have more info.

OK then.
