### ISSUE TITLE
Add yaml linters to have 5 star in ansible galaxy

### ISSUE THREAD

**Issue by staticdev** [aalaesar/install_nextcloud#121]
This is a great role and would have even more downloads if it was show as 5 star in ansible-galaxy. It is not difficult to make it, just add yamllint and ansible-lint.

@aalaesar I offer to contribute on a PR or as maintainer that if you think it is a good idea. I already did it for all the roles I am maintainer.

**Comment by wiktor2200** [comment]
I've added test PR with ansible-lint based on Github Actions: #127 
It needs some more permissions here to run, but you can see the results on my forked repo: https://github.com/wiktor2200/install_nextcloud/actions/workflows/ansible-lint.yml

**Comment by staticdev** [comment]
Done, great work @wiktor2200
