### ISSUE TITLE
Mysql error on installation using defaults

### ISSUE THREAD

**Issue by staticdev** [aalaesar/install_nextcloud#137]
Error discovered using molecule tests.

```
   TASK [aalaesar.nextcloud : [mySQL] - Update mysql root password] ***************
  fatal: [instance]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /etc/mysql/debian.cnf has the credentials. Exception message: (2003, \"Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)\")"}
```

**Comment by staticdev** [comment]
What do you think of using Mysql/MariaDb role inside this role? https://galaxy.ansible.com/geerlingguy/mysql (it has almost 3 million downloads, very well tested).

**Comment by aalaesar** [comment]
Hello @staticdev . Simplifying the role and reusing other role is  a planned feature for V2. Alongside other development

**Comment by staticdev** [comment]
> Hello @staticdev . Simplifying the role and reusing other role is a planned feature for V2. Alongside other development

@aalaesar in that case I am already having that in mind in my new PR: https://github.com/aalaesar/install_nextcloud/pull/138
