### ISSUE TITLE
Risks for configuration inconsistence between mysql_daemon and nextcloud_db_backend

### ISSUE THREAD

**Issue by aalaesar** [aalaesar/install_nextcloud#143]
hello @staticdev 
Can you elaborate the use of `mysql_daemon`  (and  `__mysql_daemon` ) for managing the mysql/mariadb server ?  
there could be cases when the user installed and used mysql instead of mariadb like in debian bullseye where it is still possible to choose beetween `default-mysql-server` and `mariadb-server`.  
if one chooses mysql, the installation will still select the proper package (as defined [here](https://github.com/aalaesar/install_nextcloud/blob/master/tasks/db_mysql.yml#L4)) but the [following task](https://github.com/aalaesar/install_nextcloud/blob/master/tasks/db_mysql.yml#L27) will fail unless `mysql_daemon` is specified as var with the same value.
It feels a bit redundant. 😕 
Have you met issues that are preventing to use `nextcloud_db_backend` instead ?

Regards
Aal.

**Comment by staticdev** [comment]
I think there is a confusion between the names of installed packages such as `default-mysql-server` and `mariadb-server` and the name of the service (daemon) `mysql_daemon`. For some reason, different OSs such as Debian 11, even if you install `mysql` will create a service called `mariadb`.

I already introduced this variable since it will be used to replace the DB installation with the role as we planned in https://github.com/aalaesar/install_nextcloud/issues/139

**Comment by aalaesar** [comment]
Thanks for your answer @staticdev
It appears that debian11 use mariadb as mysql replacement. so calling the meta package default-mysql-server effectively install mariadb-server ([source](https://packages.debian.org/bullseye/default-mysql-server))
This breaks the user's hability to choose mysql or mariadb in the role for recent OS.
at least for debian 11 but I would like to test it for other OSs.
It adds another point to removing the DB installation from the role so distribution choices won't impact the role.

My concerns is  about having 2 variables for the same service but one exposed  for users while the other is not, or not documented.

**Comment by staticdev** [comment]
I agree 100%, actually in last months I realized proper and secure instalation of Nextcloud is really complex, being db installation just another complex part.

It is a good idea to rely on separate popular roles to abstract a bit of this complexity. I will try next week to dedicate some time into adding this db role and make install_nextcloud more maintainable in this regard.
