### ISSUE TITLE
Galaxy does not handle correctly branch renaming

### ISSUE THREAD

**Issue by staticdev** [aalaesar/install_nextcloud#165]
Check https://github.com/ansible/galaxy/issues/2535

**Comment by staticdev** [comment]
Looks like it worked.

**Comment by wiktor2200** [comment]
I can see it works, but it's getting only version without `v` preffix on galaxy. I guess it should work anyways, but in same cases may break some dependencies :thinking: 
https://galaxy.ansible.com/aalaesar/install_nextcloud

**Comment by staticdev** [comment]
> I can see it works, but it's getting only version without `v` preffix on galaxy. I guess it should work anyways, but in same cases may break some dependencies, so it's just good to have it in mind thinking https://galaxy.ansible.com/aalaesar/install_nextcloud
> 
> BTW I'd prefer as it is right now without `v` - just version (most of the roles are versioned this way) ;)

I also noticed that, and was going to comment that vast majority of roles in Ansible Galaxy does not a `v`. I consider it an unintentional bugfix XD
