### ISSUE TITLE
Confusion with daily versions

### ISSUE THREAD

**Issue by noplanman** [aalaesar/install_nextcloud#18]
Looking at how the Nextcloud version can be specified, something's a bit off.

The main issue is when choosing the daily channel, namely this part:
`daily: "nextcloud-{{nextcloud_branch}}-daily-{{nextcloud_version}}.zip"`

Looking into the [daily folder](https://download.nextcloud.com/server/daily/) on the download server, this format doesn't exist.

For daily stable releases it should be something like:
`latest-stable{{ nextcloud_version_major }}.zip`

And for bleeding edge daily is should be:
`nextcloud-{{ nextcloud_version_major }}-daily-{{ ansible_date_time.date }}.zip`

I've been working on a PR for this, but I'm not sure how best to tackle it. Main issue is the date for the bleeding edge daily archives, as it's possible that the date is 1 day behind (depending on timezone), resulting in an invalid URL. For that, I was thinking of a fallback system that would go back 1 day in case the archive doesn't exist.
Other option would be to put the date in a variable, allowing to choose an specific daily version, but not sure how necessary that would be. (I guess it could be an optional thing, default being today's date, falling back to yesterday's).

What do you think?

**Comment by aalaesar** [comment]
Indeed, this uses case is badly documented/explained, and maybe I didn't used the most appropriates words.
In fact I assumed that users can write whatever they like in` {{ nextcloud_version}} `because it is free form, including any date when they want a specific daily instance.
I also wanted to use a minimum number of variables.
For the bleeding edge daily there is also the` lastest master` file pointing to the most recent daily if i'm not mistaken.
from my perspective,` {{ nextcloud_branch }} == {{ nextcloud_version_major }}`.

What I did might be a little lazy and may need some refactoring and/or to be more documented, I don't known how much you worked on this one.

**Comment by aalaesar** [comment]
I missed this point:

> The main issue is when choosing the daily channel, namely this part:
daily: "nextcloud-{{nextcloud_branch}}-daily-{{nextcloud_version}}.zip"
Looking into the daily folder on the download server, this format doesn't exist.
For daily stable releases it should be something like:
latest-stable{{ nextcloud_version_major }}.zip

Both formats exists,
The daily subfolder is veeeeery long and contains a LOT of daily versions from nextcloud 9 to 11, and master
`daily: "nextcloud-{{nextcloud_branch}}-daily-{{nextcloud_version}}.zip"` works well by specifying a date in nextcloud_version.
But, as I said before, this might be not well explained or counter-intuitive.

**Comment by noplanman** [comment]
I understand your point of not using many variables, which I totally agree with!

Yes, the daily list is really long... It's just a matter of using right variables that do the job :+1:
For example: I don't think `branch == major version`. Branch should be what it is now (`stable`, only one at the moment I think, maybe also `master`?).
Major version is basically: `"{{nextcloud_version.split('.')[0]}}"`, so this is a temporary variable to make things easier, not a separate one for the user to define.

> ...works well by specifying a date in nextcloud_version.

Yes, but it's just not correct, as specifying just the date could be any version, 9, 10, 11, master, etc. So the `nextcloud_branch` part there should really be the `nextcloud_major_version` (or master).

I think it makes sense to think this through a bit more before making a big move on this.

**Comment by aalaesar** [comment]
I've just noticed that since 15th jan -last patch release- there is a latest archive in releases for each major version.
Therefore your point make even more sense to rework the version selection tasks.

**Comment by aalaesar** [comment]
Nextcloud has added different archives, even in releases channel,
there are now cases :
- __Releases__:
  - lastest
  - lastest + major
  - full_version
- __prereleases__:
  - full_version + RC(n)
- __Daily__:
  - latest
  - latest + major_branches
  - major + daily (date)

So far I get: 
- __Update Channel__ : Releases|prereleases|daily
- __major version__: 9|10|11|...
- __full version__ number
- __RC__ number
- __date__ (for daily) version: YYYY-MM-DD
- __major branch__ (for daily) : master|stable9|stable10|...
- __"latest"__ keyword


Ideally I whould like to keep url Statically generated (as it is done by now in vars/main.yml), without using a set_fact task and conditions, and keep a minimal number of variables...
Any suggestion ? 😃

**Comment by aalaesar** [comment]
Pushed a new branch [Rework_version_selection_#18](https://github.com/aalaesar/install_nextcloud/tree/Rework_version_selection_%2318)
can you make a Rewiew of the new download variables ?

**Comment by noplanman** [comment]
@aalaesar Would be great if you could make a PR to continue the discussion, then I can comment directly on code lines.

**Comment by aalaesar** [comment]
here you go: #26
