### ISSUE TITLE
nextcloud_config_settings: Let 'php occ config:system:set' make use of switch '--type=boolean'

### ISSUE THREAD

**Issue by stevenengland** [aalaesar/install_nextcloud#187]
In the current release individual configuration options including bool ones are ment to be set like this:

```
nextcloud_config_settings:
  - { name: 'mail_smtpauth', value: 'false' }
```
But this way the boolean value will be interpreted as string by the occ command. The configured value will not be respected by Nextcloud.

So instead of
`ansible.builtin.command: php occ config:system:set {{ item.name }} --value="{{ item.value }}"`

a better solution might be:
`ansible.builtin.command: php occ config:system:set {{ item.name }} --value="{{ item.value }}" {% if item.value | type_debug == 'bool' %}--type=boolean{% endif %}`

The usage would then be:
```
nextcloud_config_settings:
  - { name: 'mail_smtpauth', value: false }
```
^-- mind the missing quotes not surrounding the bool value anymore.

**Comment by aalaesar** [comment]
Hello @stevenengland
Nice catch 😃  thank you for reporting.
I'll let you push a pull request if you want to contribute the fix to the role.
Regards.
Aal.

**Comment by stevenengland** [comment]
Hi @aalaesar , I took it as a chance to learn how to contribute to public repos :) So as I am a beginner I need some help: I checked out the repo, added a branch, made my fixes and now want to create a pull request. But I am struggeling with git and the access rights to this repo. Can you contact me and help me out? I am able to push to my own repos but I am not able to push to yours. Do I need specific rights from your side?

**Comment by stevenengland** [comment]
Hi @aalaesar , there it is ;)
