### ISSUE TITLE
Add Nextcloud apps

### ISSUE THREAD

**Issue by noplanman** [aalaesar/install_nextcloud#19]
Would be cool to be able to add Nextcloud apps that should be added on install.

Kind of like [here](https://gitlab.com/agitatedseeds/nextcloud/tree/master/files) (look at the `download.sh` and `install.sh` files).

This could be done with a simple dictionary, listing name and URL to fetch apps from. It would be up to the user to create the array with the correct URLs to the app repositories, but the ansible script could take care of the installation and enabling them.

Something like this:
```
nextcloud_apps:
  calendar: https://github.com/nextcloud/calendar/releases/download/v1.4.1/calendar.tar.gz
  contacts: https://github.com/nextcloud/contacts/releases/download/v1.5.2/contacts.tar.gz
  twofactor_totp: https://github.com/nextcloud/twofactor_totp/releases/download/0.5.0
/twofactor_totp.tar.gz
  ...
```

And in the Nextcloud download and installation tasks, the processing would be done, in the same way as the 2 scripts from above.

**Comment by aalaesar** [comment]
Hi
It could be relatively simple to add this steps at the end of the role.
I'll look into it this week for idempotence and stability.

What about the case when the user specify an app already available in the nextcloud downloads ? should the role download it again ?

**Comment by noplanman** [comment]
> should the role download it again?

Before the package download/install, we could call `sudo -u www-data php occ app:list` and register the output to a temporary variable.
Then, we can use that as a reference of what is already installed 👍
