### ISSUE TITLE
Remove the `always` tag from the role.

### ISSUE THREAD

**Issue by nono-lqdn** [aalaesar/install_nextcloud#191]
Hello,

First of all, thanks for this role, is has been very useful to us at [La Quadrature Du Net](https://lqdn.fr/nous).

I'm opening this issue to ask if I can make a pull request to remove the `always` tag that is being used in this role. 

I figure it is not necessary to have such a tag on a role. It induces issues when running parts of a playbook with many roles on a host with this role, as it might run part of this role when it is not needed, or when it is needed that it _must not_ run. 

I know I can skip the tasks altogether with the `--skip-tags always` option, but [per the documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#special-tags-always-and-never), it is bad practice as it will also skip fact gathering.

Overall, why does this role need the `always` tag ? If it does not, can I remove it & request a pull to apply this change in the futur and avoid a fork ?

Thanks again, 

nono

**Comment by wiktor2200** [comment]
Hello Nono! In my opinion it makes sense nowadays. `tags: always` exisits only in two places in role in one file: https://github.com/aalaesar/install_nextcloud/blob/main/tasks/main.yml#L6 and line 11.
I think it's some very old leftover (committed 6 years ago) and can be deleted. 
@aalaesar could you confirm?

**Comment by aalaesar** [comment]
hello @nono-lqdn , thank you for your feedback 😄 
Indeed, It looks like old stuff.
I'll remove all the remaining tags from the role

**Comment by aalaesar** [comment]
@nono-lqdn  @wiktor2200 
just realized the tag always is here to guarantee systems facts are loaded when the tag `install_apps` is used
so either:
- I drop the tag `install_apps` and cleanup the rest, but it removes the ability to use the role to install only apps. (don't know if anyone uses this)
- we rework how system facts are setup with a _no tasks data structure_ so we can drop the tags always but that's more complex
- @nono-lqdn As I understand you need sometime to skip to run the entire role,  you can use a workaround in your playbooks to make all tasks inherit a custom tag when you call/import/include the role. the tag `always` has less priority than any other one when using `--skip-tags`
   - if you use `import_role` in your playbook, all tasks from the role inherit the tags you put here so you can still use `--skip-tags <your-tag>` to skip the role entirely
   - if you use `include_role`, you must specify the tag with the [apply parameter](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_role_module.html#parameter-apply)  to _force inheritence_ and use `--skip-tags <your-tag>` to skip the role entirely
   - if you use the `roles` keyword in your playbook, I recommend to use include_role instead 😃 

regards

**Comment by wiktor2200** [comment]
It makes sense. I think there is one more possible solution. Replace tag `always` with `install_apps`. 
So it this case, when run without any tag it would run whole role, but when tag `install_apps` would be provided it will run only 3 steps (these two from main + installing apps).

**Comment by staticdev** [comment]
@aalaesar since we are making a collection, maybe we can extract the apps code and make a role with the responsibility to install/uninstall/disable/enable nextcloud apps =p

**Comment by aalaesar** [comment]
> @aalaesar since we are making a collection, maybe we can extract the apps code and make a separate role with the responsibility to install/uninstall/disable/enable nextcloud apps =p

 Actually I have in mind to add more modules than roles. Module would be for simple, discreet admin action, precisely like managing  one application or updating a config value,  while roles should be developed for complex workflows like installation, upgrade, backup, migration etc of nextcloud.
The roles themselves  should use as much as possible the modules instead of relying  on the command or shell module to run the occ commands.
First phase of development  should be to add as many modules as necessary to replace most of the command tasks using occ in install_nextcloud, and simplify  the role in the process.

**Comment by nono-lqdn** [comment]
Thanks a lot !
