### ISSUE TITLE
ansible-galaxy install error

### ISSUE THREAD

**Issue by wiktor2200** [aalaesar/install_nextcloud#196]
When I'm trying to run:
```
ansible-galaxy install aalaesar.install_nextcloud
```
on clean host, I'm getting this error

```
Starting galaxy role install process
- downloading role 'install_nextcloud', owned by aalaesar
[WARNING]: - aalaesar.install_nextcloud was NOT installed successfully: Unable to compare role versions (v1.2, v1.2.1, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.4.0, v1.4.1, v1.5.0, 1.6.0, 1.7.0) to determine the
most recent version due to incompatible version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
So I had to install it with version specified:
```
ansible-galaxy install aalaesar.install_nextcloud,1.7.0
```
But it's not default option nor mentioned anywhere in our README.

I think it's caused by new versioning format introduced by automated galaxy releases: https://github.com/aalaesar/install_nextcloud/pull/163
Do you have idea how can it be fixed? I suppose, one of this methods: remove `v` from old ones, add `v` to newer (but will require changes in this repo and automation flow) or marking old one as deprecated? 

WDYT @staticdev @aalaesar?

**Comment by aalaesar** [comment]
Hello. Hmmm. I'm  not sure.
Renaming the previous tags maybe ?

**Comment by wiktor2200** [comment]
Is it possible to rename it or do they need to be deleted and re-created? Could you do that on Ansible Galaxy account?

**Comment by mihailstoynov** [comment]
Until fixed, this works:
`roles:
- {src: aalaesar.install_nextcloud, version: "1.7.0" }            # for nextcloud
`

**Comment by staticdev** [comment]
> Hello. Hmmm. I'm not sure. Renaming the previous tags maybe ?

If we rename the old ones, it is reflected also on Ansible Galaxy? Is there maybe a way to do it directly there?

**Comment by aalaesar** [comment]
> If we rename the old ones, it is reflected also on Ansible Galaxy?

Yes that's the unknown factor. I'll try by renaming one tag

> Is there maybe a way to do it directly there?

I don't know how ansible-galaxy deal with tags changed _at posteriori_

> Speaking of which, we can merge #198 and then release a 1.8.0 version with #200. We did already a good bunch of changes.

#198 will **not** be merged into main (but 2.0-dev)  so it won't be in the release
but I'll  rather wait for #188
#194 is also almost done
I think it would make sense to get all the app management PR  done for 1.8.0

**Comment by wiktor2200** [comment]
I agree with @aalaesar, we should wait for #188 and #194 (as they are almost done) and then add them to 1.8.0.
Could you check if it's possible to modify tags directly on galaxy?

**Comment by aalaesar** [comment]
> Could you check if it's possible to modify tags directly on galaxy?
nope. no specific managment.
 everything is managed in the repo. I'll test renaming on the oldest tag, `v1.2.1` 6 years ago. It won't be a big loss if things goes bad .
I just not sure I can trigger manual imports again to see if it works as it broked when we renamed the master branch

**Comment by wiktor2200** [comment]
I still can see tag named v1.2.1 in both Github and Galaxy, weird.

**Comment by aalaesar** [comment]
> I still can see tag named v1.2.1 in both Github and Galaxy, weird.

I took my time to do it properly but it worked :smiley: so galaxy is just parsing tags after each import. simple yet effective

**Comment by wiktor2200** [comment]
That's a great news! :1st_place_medal:

**Comment by wiktor2200** [comment]
It's fixed now. Using simple command works as expected.
```
ansible-galaxy install aalaesar.install_nextcloud
```
@aalaesar Thanks for your help! :)

**Comment by aalaesar** [comment]
All tags renamed and imported to galaxy.
Only side effect is to github to drop all old releases notes based on tags that has been renamed.
But I can live with that :sunglasses:
