### ISSUE TITLE
APCu not available for local cache

### ISSUE THREAD

**Issue by MaxiReglisse** [aalaesar/install_nextcloud#204]
nextcloud deployment failed due to the following error: APCu not available for local cache.

    changed: [cloud-archives.inframshe.univ-fcomte.fr] => (item={'name': 'memcache.local', 'value': '\\OC\\Memcache\\APCu'})
    failed: [cloud-archives.inframshe.univ-fcomte.fr] (item={'name': 'open_basedir', 'value': '/dev/urandom'}) => {"ansible_loop_var": 
    "item", "changed": true, "cmd": ["php", "occ", "config:system:set", "open_basedir", "--value=/dev/urandom"], "delta": "0:00:00.069124",
     "end": "2023-02-04 09:15:50.869175", "item": {"name": "open_basedir", "value": "/dev/urandom"}, "msg": "non-zero return code", 
    "rc": 1, "start": "2023-02-04 09:15:50.800051", "stderr": "", "stderr_lines": [], "stdout": "An unhandled exception has been 
    thrown:\nOCP\\HintException: [0]: Memcache \\OC\\Memcache\\APCu not available for local cache (Is the matching PHP module 
    installed and enabled?)", "stdout_lines": ["An unhandled exception has been thrown:", "OCP\\HintException: [0]: 
    Memcache \\OC\\Memcache\\APCu not available for local cache (Is the matching PHP module installed and enabled?)"]}

To solve this problem, I set the variable apc.enable_cli=1 in the file /etc/php/8.1/cli/conf.d/20-apcu.ini

    root@cloud-archives:~ # grep -r apc.enable_cli /etc/php/
    /etc/php/8.1/cli/conf.d/20-apcu.ini:apc.enable_cli=1
    /etc/php/8.1/cli/php.ini:apc.enable_cli = 1
    /etc/php/8.1/apache2/conf.d/20-apcu.ini:apc.enable_cli=0
    /etc/php/8.1/fpm/conf.d/20-apcu.ini:apc.enable_cli=1

It would probably be easier to do the same in the php.ini files... what do you think about it?

I take this opportunity to ask you why you add spaces in the initialization of this variable.

    root@nfs1-server:/usr/local/ansible-admin (master) # grep -r "apc.enable_cli = 1" ../galaxy-roles/
    ../galaxy-roles/aalaesar.install_nextcloud/tasks/http_nginx.yml:    line: "apc.enable_cli = 1"
    ../galaxy-roles/aalaesar.install_nextcloud/tasks/http_apache.yml:    line: "apc.enable_cli = 1"

A big thank you for the work done with this Ansible role!

Ernest.

**Comment by staticdev** [comment]
@aalaesar since main now has collection structure, we may need a parallel branch to bugfix here. Problem is the automation se have is not perpared to uploading to Galaxy a different branch.

**Comment by aalaesar** [comment]
> @aalaesar since main now has collection structure, we may need a parallel branch to bugfix here. Problem is the automation we have is not prepared to uploading to Galaxy a different branch.
> 
> Maybe easier way is create a collection branch with current code and revert main to last release so we fix these issues.

No problem @staticdev that's already  the case 😃
 the collection is in another branch. __main is still a role__. Bug fixing can proceed as normal and Galaxy import haven't  changed yet and is still working  fine.
I'll just have lot of conflicts to solve when releasing the v2.0 😅

**Comment by wiktor2200** [comment]
Hello @MaxiReglisse! 
It is already set (since forever in role) and main `php.ini` file is modified by role.
For Apache2: https://github.com/aalaesar/install_nextcloud/blob/main/tasks/http_apache.yml#L5
For Nginx: https://github.com/aalaesar/install_nextcloud/blob/main/tasks/http_nginx.yml#L26
What is more APC package is installed: https://github.com/aalaesar/install_nextcloud/blob/main/tasks/php_install.yml#L45

I suppose there is some problem with running this role. How do you use it, through galaxy or cloned from this repo? Could you give us some insights for troubleshooting?

**Comment by MaxiReglisse** [comment]
Hello @Aalaesar and @Staticdev !
I only use Ansible Galaxy repositories. I guess the error comes from the fact that I tried to install PHP with a php role instead of relying on install_nextcloud to take care of everything.
My apologies for the background noise... and my thanks for this playbook which is really great.
