### ISSUE TITLE
ansible-lint behaving differently between CI and installed pre-commit hooks

### ISSUE THREAD

**Issue by aalaesar** [aalaesar/install_nextcloud#207]
Hello there !
I actually can't commit locally with pre-commit installed because of ansible-lint errors.
That could be a normal behaviour **if it was'nt errors about already commited code** that did not triggered our CI tests.
I've looked at https://github.com/ansible/ansible-lint-action to see if there were any config in particular but found nothing, as expected because that's how galaxy is running it.

I forced installed the same ansible-lint version used in the release for 6.0.0 to 6.11.0 but every time I got the same errors: 

```bash
$ git status
Sur la branche nextcloud-rebranding
Modifications qui seront validées :
  (utilisez "git restore --staged <fichier>..." pour désindexer)
        modifié :         galaxy.yml

$ git commit -S -m "update collection namespace and name"
yamllint.................................................................Passed
Ansible-lint.............................................................Failed
- hook id: ansible-lint
- exit code: 2
[...]
WARNING  Listing 16 violation(s) that are fatal
# I get a bunch of thoses:
no-free-form: Avoid using free-form when calling module actions. (ansible.builtin.command) (warning)
roles/install_nextcloud/tasks/db_mysql.yml:33 Task/Handler: [mySQL] - Get list of hosts for the root user.

# and then the fatal errors : 
name[template]: Jinja templates should only be at the end of 'name'
roles/install_nextcloud/tasks/nc_apps.yml:10 Task/Handler: [App] - Verify the yaml declaration for the app "{{ nc_app_name }}"

name[template]: Jinja templates should only be at the end of 'name'
roles/install_nextcloud/tasks/nc_apps.yml:17 Task/Handler: [App] - Install from the official app-store app: "{{ nc_app_name }}"

name[template]: Jinja templates should only be at the end of 'name'
roles/install_nextcloud/tasks/nc_apps.yml:26 Task/Handler: [App] - Download Archive in apps folder from "{{ nc_app_source }}"

name[template]: Jinja templates should only be at the end of 'name'
roles/install_nextcloud/tasks/nc_apps.yml:38 Task/Handler: [App] - Enable the application "{{ nc_app_name }}"

name[template]: Jinja templates should only be at the end of 'name'
roles/install_nextcloud/tasks/nc_apps.yml:47 Task/Handler: [App] - Configure the application "{{ nc_app_name }}"

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental
  - name[template]  # Rule for checking task and play names.

                       Rule Violation Summary                       
 count tag            profile  rule associated tags                 
     5 name[template] moderate idiom                                
    11 no-free-form   moderate syntax, risk, experimental (warning) 

Failed after basic profile, 1/5 star rating: 5 failure(s), 11 warning(s) on 57 files.
```

So what's the difference between the action run in the CI and the pre-commit hook ?
Can't find out.

Regards,
Aal.

**Comment by aalaesar** [comment]
Looks like a bug.
pre-commit hook is passing now  with v6.11.0

**Comment by wiktor2200** [comment]
When I saw that, I thought about dependabot automatically update pre-commit hooks, but then I've dug a little bit and there are two open issues already (more than 3 years now), so it probably won't happen :(
* https://github.com/dependabot/dependabot-core/issues/1524
* https://github.com/dependabot/dependabot-core/issues/2040

But I've found this fancy github action:
https://github.com/browniebroke/pre-commit-autoupdate-action

@aalaesar @staticdev
WDYT, is it worth adding new/additional automation tool to mitigate similar problems in the future?

**Comment by staticdev** [comment]
> When I saw that, I thought about dependabot automatically update pre-commit hooks, but then I've dug a little bit and there are two open issues already (more than 3 years now), so it probably won't happen :(
> 
>     * [Support pre-commit dependabot/dependabot-core#1524](https://github.com/dependabot/dependabot-core/issues/1524)
> 
>     * [Support bumping dependencies in .pre-commit-config.yml dependabot/dependabot-core#2040](https://github.com/dependabot/dependabot-core/issues/2040)
> 
> 
> But I've found this fancy github action: https://github.com/browniebroke/pre-commit-autoupdate-action
> 
> @aalaesar @staticdev WDYT, is it worth adding new/additional automation tool to mitigate similar problems in the future?

I am in favor =) I was one for the first to upvote the issues that you mentioned XD

**Comment by aalaesar** [comment]
all right, looks simple enough
