### ISSUE TITLE
a little direction using Vagrant and Ansible to create working instance

### ISSUE THREAD

**Issue by wgregori** [aalaesar/install_nextcloud#21]
I'm looking for a little direction using Vagrant and Ansible .. I've read a number of tutorials and understand how it works... but I can't seem to make it work.  I need some help directing Vagrant to use your ansible Role...  The config files below succeed and creating an instance of ubuntu but it is not provisioned with Nextcloud.  Thanks for any direction that you might provide!

Here are my files:

**Vagrantfile:** 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

Vagrant.configure(2) do |config|

  # VM Image - Ubuntu v14.04
  config.vm.box = "ubuntu/trusty64"

  # VM Resources
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus   = 1
  end

  # Provision with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end

**Vagrant.yml:**
- hosts: all
  roles:
   - role: install_nextcloud-master

My root directory looks like this:
Vagrant
->ubuntu
->install_nextcloud-master

**Comment by aalaesar** [comment]
Hello @wgregori 
sorry I can't help you on this subject as I don't use Vagrant (for now)
Maybe you'll be more lucky on [Stackoverflow](http://stackoverflow.com/search?q=vagrant+AND+ansible)
I'm closing as The subject is not an issue with the role or a suggestion.
Best luck on fixing your issue.,
Regards, Aal.
