### ISSUE TITLE
debian breaks occ when using become_method=su

### ISSUE THREAD

**Issue by aalaesar** [aalaesar/install_nextcloud#22]
on debian 8.7 environments not using sudo but su instead, the following error appears:
```
TASK [install_nextcloud : [NC] - Run occ installation command] *****************
fatal: [debian8]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to xx.xx.xx.xx closed.\r\n", "module_stdout": "This account is currently not available.\r\n", "msg": "MODULE FAILURE"}
```
cause : the websrv user is not allowed to login/run command. (bash is /nologin)

running on the CLI gave the same error: 
```
# su www-data -c " php /opt/nextcloud/occ"
This account is currently not available.
```
A clean workaround is : 
`su www-data -s /bin/sh -c " php /opt/nextcloud/occ"` but hard to do in ansible without breaking theocc  tasks

a dirty workaround is changing the shell for the websrv user
`chsh -s /bin/sh www-data` as  root

**Comment by aalaesar** [comment]
`ansible -i testing_plays/testing debian8 -m command -a 'php /opt/nextcloud/occ' --become-user=www-data  --become-method=su`
is working.... :sob:

**Comment by pheanex** [comment]
Your suggestion with the temporary chsh works for me, but this is still an issue

**Comment by aalaesar** [comment]
Indeed,
I haven't worked  on this for some times. I'll look for some new ansible feature allowing  to specify  a shell with become user .
So this is still happening  with the latest ansible  versions?

**Comment by pheanex** [comment]
Im using it with ansible 2.2.1.0 .... so not the very latest, but coming with debian testing
