### ISSUE TITLE
Make better use of occ

### ISSUE THREAD

**Issue by noplanman** [aalaesar/install_nextcloud#24]
Peeking into (what seems) the only other usable Nextcloud Ansible project, I must say that using occ is a better way of manipulating the configuration.
Look [here](https://github.com/Phill93/ansible-nextcloud/blob/master/tasks/main.yml#L85)

This prevents any breakage of the file, as it's managed by NC itself.

~Also, it would be great in the installation script would run even if NC is already installed, as that would allow for configuration changes to take place or NC core updates.
Alternatively, there could be an extra task file for this.~
Edit: Just discovered your `upgrade-nextcloud` repo

**Comment by aalaesar** [comment]
Indeed, much more reliable.
so i'm reading the [nextcloud doc](https://docs.nextcloud.com/server/11/admin_manual/configuration_server/occ_command.html#config-commands), I find it a little confusing on how it manages the config file.
I'll have to fix #22 first though.

**Comment by aalaesar** [comment]
hello @noplanman . I hope you are doing well
2.0 will release soon.
with it, the repository will become a collection with the install_nextcloud role and the new module run_occ for running directly occ commands withouts the become hacking around the tasks. But the code base of the module will also be the foundation for all future  modules of this collection.
first developpments efforts will be to gradually develop modules to replace command tasks in the role.
So I'm closing this issue as it is now fully part of the development strategy of this repository.
Take care
Aal.
