### ISSUE TITLE
Add letsencrypt option for TLS cert generation.

### ISSUE THREAD

**Issue by aalaesar** [aalaesar/install_nextcloud#4]
For now no support for cerbot/lestencrypt.
let's add this.

**Comment by MartinVerges** [comment]
I maybe can provide you a pull request to support it, but would push ansible requirement to 2.2/2.3 because I use the ansible internal version and nit certbot

**Comment by jaywink** [comment]
One option is also to provide LetsEncrypt certs via a dependency role. For example [this one](https://github.com/jaywink/ansible-letsencrypt).

Basically the ansible-letsencrypt role just needs to be executed before the nextcloud role and nextcloud role needs to specify the installed cert locations which are known for letsencrypt, ie:

    SSLCertificateFile /etc/letsencrypt/live/{{ domain }}/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/{{ domain }}/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/{{ domain }}/chain.pem

Just an idea if you want to keep this role less complex - CertBot itself has a lot of ways to configure it for different usages and it's not trivial to cover all the cases.

**Comment by aalaesar** [comment]
Hi,
@MartinVerges : Can you tell me more about `ansible internal version` ?

@jaywink : I have thought about this for quite some time.
Using an external role  for let's encrypt certificates is already possible as you describe it by using 
```YAML
nextcloud_tls_cert_method: "installed"
```
as in readme's case 2.
So, it whould be just removing this planned feature.
However it doesn't satisfy me. I initialy wanted the role to perform a simple certificate request in order  to allow a quick installation for a public nextcloud instance.

> CertBot itself has a lot of ways to configure it for different usages and it's not trivial to cover all the cases.

Yes and that's why I'm still not  working on this one. :(
This, and lot less free time available.

Regards.

**Comment by MartinVerges** [comment]
@aalaesar you can find it on https://docs.ansible.com/ansible/letsencrypt_module.html. It is working and I implemented it on the role https://github.com/First-Colo-GmbH/ansible-haproxy (not yet finished). It's only available from ansible 2.2 on but some modules for openssl are coming with 2.3 so it's upcoming feature of ansible without the need for certbot

**Comment by aalaesar** [comment]
This is very insteresting.
As it is an ansible 2.2 dependency, I think it is better to postpone this feature for 1.1 in order to stay dependent to Ansible 2.0
Thank you @MartinVerges.

**Comment by aalaesar** [comment]
Soooooooooooooooo...
 it has been 3years and yet it didntt event feels as a important feature for me or anyone helping on the role.

Let's keep it simple.  
using `nextcloud_tls_cert_method: installed` is effective and don't make the role bloated.

letsencrypt certs can be generated and installed by any means this way.
So closing
