### ISSUE TITLE
Install Fails on Debian 9.4

### ISSUE THREAD

**Issue by arenius** [aalaesar/install_nextcloud#41]
The error I receive is:

TASK [aalaesar.install_nextcloud : [NC] - Run occ installation command] ********
fatal: [nextcloud]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1523469539.2008-15810294841448/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1523469539.2008-15810294841448/command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

TASK [aalaesar.install_nextcloud : [Unfix su] - Check current shell for www-data.] ***
fatal: [nextcloud]: FAILED! => {"msg": "The conditional check 'ansible_become_method == \"su\"' failed. The error was: error while evaluating conditional (ansible_become_method == \"su\"): 'ansible_become_method' is undefined\n\nThe error appears to have been in '/Users/greg/code/ansible/roles/external/aalaesar.install_nextcloud/tasks/unfix_su.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: \"[Unfix su] - Check current shell for {{ nextcloud_websrv_user }}.\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

I think the issue is described here:
https://stackoverflow.com/questions/36646880/ansible-2-1-0-using-become-become-user-fails-to-set-permissions-on-temp-file

If I ensure that setfacl is installed prior to running the nextcloud role everything works as expected.

**Comment by privateseabass** [comment]
This bug is on buster, as well.

Don't know if it is desireable, but my workaround was installing acl to the system.
Is there a reason you may not want this?
I installed it on a Pi, otherwise, so I don't know if that would make a difference.
