### ISSUE TITLE
Failure when changing "nextcloud_trusted_domain"

### ISSUE THREAD

**Issue by klemens-u** [aalaesar/install_nextcloud#62]
Initial setup works fine with this config:

```
    nextcloud_trusted_domain:
      - "fresh1804srv"
    nextcloud_webroot: "/var/www/nextcloud"
    nextcloud_data_dir: "/srv/nextcloud"
```

But when I change the the trusted_domain the following errors occur:
```
    nextcloud_trusted_domain:
      - "test123"
```

```
TASK [install_nextcloud : [NC] - Run occ installation command] ******************************************************************************************
 [WARNING]: Unable to use /var/www/.ansible/tmp as temporary directory, failing back to system: [Errno 13] Permission denied: '/var/www/.ansible'

fatal: [fresh1804srv]: FAILED! => {"changed": true, "cmd": ["php", "occ", "maintenance:install", "--database=mysql", "--database-host=127.0.0.1", "--database-name=nextcloud", "--database-user=ncadmin", "--database-pass=Jp0QfAZ.FLO_jfw.ksTZ", "--admin-user=admin", "--admin-pass=X:yrlUBXK,", "--data-dir=/srv/nextcloud"], "delta": "0:00:00.321365", "end": "2019-02-28 11:56:08.655059", "msg": "non-zero return code", "rc": 1, "start": "2019-02-28 11:56:08.333694", "stderr": "", "stderr_lines": [], "stdout": "The username is already being used", "stdout_lines": ["The username is already being used"]}

TASK [install_nextcloud : Unfix su issue with occ] ******************************************************************************************************
fatal: [fresh1804srv]: FAILED! => {"msg": "The conditional check 'ansible_become_method == \"su\"' failed. The error was: error while evaluating conditional (ansible_become_method == \"su\"): 'ansible_become_method' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/install_nextcloud/tasks/nc_installation.yml': line 71, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  rescue:\n    - name: Unfix su issue with occ\n      ^ here\n"}
	to retry, use: --limit @/etc/ansible/site.retry

PLAY RECAP **********************************************************************************************************************************************
fresh1804srv               : ok=43   changed=1    unreachable=0    failed=2  
```

**Comment by klemens-u** [comment]
Furthermore it is discussable if all the credentials should change in this case. For example the contents in "/etc/ansible/nextcloud_instances"

**Comment by aalaesar** [comment]
> Furthermore it is discussable if all the credentials should change in this case. For example the contents in "/etc/ansible/nextcloud_instances"

hello @klemens-u I'm not sure what you mean. Can you elaborate.

Looking into what could cause ansible to fail here.

Regards
Aal.

**Comment by klemens-u** [comment]
> I'm not sure what you mean. Can you elaborate.

Of course, sorry for beeing unclear. If one changes the trusted domain:
- A new folder is created in "/etc/ansible/nextcloud_instances"  (better rename it?)
- All the passwords are changed

**Comment by aalaesar** [comment]
Just passing on the opened issues. :flushed:
I'm so sorry, :flushed:  I'd swear I answered you 3 months ago

I didn't tested the role for configuration update or changing the server's domain' s name.
For you specific problem
As the file's location is based on the nextcloud instance name you can specify the variable `nextcloud_instance_name` to override the default value (first item of `nextcloud_trusted_domain`)
and you'll keep your passwords.

However, I wouldn't recommend  to rely on the ansible password lookup to store credential for production instance. The password are in clear text in files that can be lost /copied etc.

Regards. Aal
