### ISSUE TITLE
Detail generating conf files with IPv6 addresses

### ISSUE THREAD

**Issue by santiagomr** [aalaesar/install_nextcloud#65]
Hi, I have an inconvenience installing Nexcloud (over Apache) on a server with IPv6 address.

With my variable `nextcloud_trusted_domain` defined at this way:
```yaml
nextcloud_trusted_domain:
  - "{{ ansible_fqdn }}"
  - "{{ ansible_default_ipv4.address }}"
  - "{{ ansible_default_ipv6.address }}"
```
The Nextcloud site conf file is defined like this:
```xml
<VirtualHost *:80>
  ServerName my-server.org
  Redirect permanent / https://my-server.org/
</VirtualHost>
<VirtualHost *:80>
  ServerName 200.100.20.10
  Redirect permanent / https://200.100.20.10/
</VirtualHost>
<VirtualHost *:80>
  ServerName 200:100:a::10
  Redirect permanent / https://200:100:a::10/
</VirtualHost>
```
### **Being necessary in the permanent redirection, add the brackets around the IPv6:**
```
  Redirect permanent / https://[200:100:a::10]/
```

Something similar happens in `config/config.php`:
```php
  'trusted_domains' => 
  array (
    0 => 'my-server.org',
    1 => '200.100.20.10',
    2 => '200:100:a::10',      // Needs to be modified to:  2 => '[200:100:a::10]',
  ),
```
I'm trying to find an adequate solution for the brackets to be added when appropriate in the templates. If I succeed, I send you the proposal.

**Comment by aalaesar** [comment]
Hello @santiagomr 
I think you are looking for this : https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#wrapping-ipv6-addresses-in-brackets
Test it with:
```yaml
nextcloud_trusted_domain:
  - "{{ ansible_fqdn }}"
  - "{{ ansible_default_ipv4.address }}"
  - "{{ ansible_default_ipv6.address | ipwrap }}"
```
should works and can be easily merged to the templates.

**Comment by santiagomr** [comment]
Good tip. `ipwrap` solves the problems, but can not be used directly in the` nextcloud_trusted_domain` definition. If we do, the apache configuration file is generated like this:
```xml
<VirtualHost *:80>
  ServerName [200:100:a::10]
  Redirect permanent / https://200:100:a::10/
</VirtualHost>
```
The brackets in `ServerName` are a syntax error that doesn't let Apache start

[This would be the way to use it without errors.](https://github.com/UdelaRInterior/install_nextcloud/commit/9519df6828900ab3567cbc8726e6f1e7ce6ebd64)

Another detail is that to use `ipwrap` it is necessary install the netaddr Python library

**Comment by aalaesar** [comment]
Nice :+1: 
I let you make the PR.
you'll need to rebase first, I added a bunch of commits today
