### ISSUE TITLE
Parameterize client_max_body_size

### ISSUE THREAD

**Issue by jcalonso** [aalaesar/install_nextcloud#67]
Would it be possible to allow to set the client_max_body_size on Nginx, so that its possible to upload files bigger than 512M?

https://github.com/aalaesar/install_nextcloud/blob/97ae6db70f1636be985748c3a5100cd113738e99/templates/nginx_nc.j2#L93

**Comment by aalaesar** [comment]
Hello @jcalonso, sorry for the late answer
thnak you for the suggestion, it's a great idea
I'll look for an equivalent for apache2 this week and implement it ASAP.

**Comment by jcalonso** [comment]
Thank you @aalaesar for writing this Ansible role :)

**Comment by aalaesar** [comment]
Had five minutes to look into it:
- Apache has `LimitRequestBody` (in Bytes), unlimited by default (0), Maximum is 2G (in bytes)
- Nginx has `client_max_body_size `(human notation), 1m by default, can be disabled with 0,  no maximum value documented  

Conclusion:  
Currently inconsistent configuration between apache and nginx in the role.

Action required:  
new field : 
- `nc_max_upload_size` or something like that.
- human notation (use filter `human_to_bytes` for apache)
- **default: 512m ?**
- for apache check max value and fail is greater than 2G OR just disable it
