### ISSUE TITLE
The PHP memory limit is below the recommended value of 512MB.

### ISSUE THREAD

**Issue by mihailstoynov** [aalaesar/install_nextcloud#73]
The error:
The PHP memory limit is below the recommended value of 512MB.

The solution:
Change
memory_limit = 128M
to
memory_limit = 1G

In `/etc/php/7.2/fpm/php.ini`
then restart:
`systemctl restart php7.2-fpm.service && systemctl restart nginx`

Probably should be a configurable variable in the role?

**Comment by aalaesar** [comment]
Indeed,
I think php settings need refactoring:

- [ ] remove obsolete version (drop support for ubuntu 14, debian 8)
- [ ] simplify php definition on the role to allow easy multi php version support
- [ ] allow any custom php parameter
- [ ] application isolated php settingsmulti version

**Comment by staticdev** [comment]
This issue can be closed on the next release, since current release has a fix but is broken.
