### ISSUE TITLE
if I add ssl to an existing installation, it does not restart the server (no handler?)

### ISSUE THREAD

**Issue by mihailstoynov** [aalaesar/install_nextcloud#74]
So I have an installation with:
```
nextcloud_install_tls: false
nextcloud_tls_enforce: false
```

When I change it to:
```
nextcloud_install_tls: true
nextcloud_tls_enforce: true
nextcloud_tls_cert_method: "self-signed"
```
It doesn't restart the nginx.
Probably a missing handler?

**Comment by aalaesar** [comment]
🤔 it should reload nginx :
[tasks/http_nginx.yml#L104](https://github.com/aalaesar/install_nextcloud/blob/master/tasks/http_nginx.yml#L104)

[handlers/main.yml#L13](https://github.com/aalaesar/install_nextcloud/blob/master/handlers/main.yml#L13)

**Comment by aalaesar** [comment]
is it not enough for reloading the configuration ?

If the play fails before finishing the role, the handlers are not run and therefore not triggered during next play

do you have logs ?

**Comment by mihailstoynov** [comment]
No logs. Completed successfully. Didn't fail.
I guess we can close this one since no logs.

**Comment by aalaesar** [comment]
Did nginx applied the new configuration after  passing the role or did you had to reboot it manually ?
