### ISSUE TITLE
Custom PHP version

### ISSUE THREAD

**Issue by mivek** [aalaesar/install_nextcloud#87]
In the README, it is written that the PHP version can be set with the variable `php_version` however the variable is not used in any file.
The PHP version is in fact defined in the `vars` folder with the `php_ver`, is bound to the  OS and distribution version and it is not possible to override the value with a custom value in the playbook.

I think either the README should be updated or the `php_ver` should be moved to the default to let the client use a custom version of PHP.

What do you think?

**Comment by privateseabass** [comment]
Made a pull request that changes the readme to say `php_ver` as suggested.
I'm not the maintainer, but I don't see why not just change the variable name.

Also, ansible ranks variables in a particular order of importance, and defaults are lowest on that chain. So if one makes a `php_ver` in defaults, it will be overwritten, as later the playbook looks for a new value to set it to in the `vars` folder.
As described here for [Ansible variable precidence](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

https://github.com/aalaesar/install_nextcloud/pull/88#issue-383932523

**Comment by aalaesar** [comment]
Hi @mivek , @privateseabass ,

it seems that feature has been lost during the "support multi OS" PR

This is a regression, I'll look to restore it ASAP.

@as suggested by @privateseabass, you can use ansible's variable precedences  as a workaround to specify a custom version.

**Comment by privateseabass** [comment]
#88 
This fixed the issue, right?
Or are you wanting the custom version of php in the defaults?

**Comment by mivek** [comment]
Indeed #88 fixes the issue. I will wait for the fix of @aalaesar so that the variable can be defined in the defaults

**Comment by aalaesar** [comment]
Fixed by #88 merge
